## Activity 03: Filtering, Sorting, and Reshaping

Following up on the last activity, we are asked to deliver some more complex operations.   
We will, therefore, continue to work with the same dataset, our `normal_distribution.csv`.

#### Loading the dataset

In [2]:
# importing the necessary dependencies
import numpy as np

In [3]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

---

#### Filtering

To get better insights into our dataset, we want to only look at the value that fulfills certain conditions.   
Our client reaches out to us and asks us to provide lists of values that fulfills these conditions:
- all values greater than 105 (>105)
- all values that are between 90 and 95 (>90 and <95)
- the indices of all values that have a delta of less than 1 to 100 (x-100 < 1)

In [7]:
# values that are greater than 105
[el for el in dataset.flat if el > 105]

[107.43534677,
 105.7197853,
 110.18889465,
 105.95297652,
 106.54654286,
 107.22482426,
 113.42090475,
 105.48508838,
 106.1472841,
 105.85269352,
 108.57980357,
 106.71751618,
 106.39798503,
 106.83273763,
 106.47551845,
 105.30350449,
 106.03868807,
 110.44484313,
 106.6471081,
 105.0320535,
 107.02874163,
 105.07475277,
 106.57364584,
 107.22482426,
 107.19119932,
 108.09423367,
 109.40523174,
 106.11454989,
 106.57052697,
 105.13668343,
 105.37011896,
 110.44484313,
 105.86078488,
 106.89005002,
 106.57364584,
 107.40064604,
 106.38276709,
 106.46476468,
 110.43976681,
 105.02389857,
 106.05042487,
 106.89005002]

In [8]:
# values that are between 90 and 95
[el for el in dataset.flat if el >=90 and el <= 95]

[92.02628776,
 92.9267508,
 92.65657752,
 93.87155456,
 90.93318132,
 91.37294597,
 91.6604946,
 93.37126331,
 94.20019732,
 93.24376389,
 94.35373179,
 92.5748759,
 91.37294597,
 92.87730812,
 93.87155456,
 92.75048583,
 93.97853495,
 91.32093303,
 92.0108226,
 93.18884302,
 93.83969256,
 94.5081787,
 94.59300658,
 93.04610867,
 91.6779221,
 91.37294597,
 94.76253572,
 94.57421727,
 94.11176915,
 93.97853495]

> **Note:**    
Conditional filtering can be done either using the brackets syntax or NumPys `extract` method

In [9]:
# indices of values that have a delta of less than 1 to 100
np.extract(np.less(dataset,100), dataset)

array([99.14931546, 97.85230675, 98.74986914, 98.80833412, 96.81964892,
       98.56783189, 92.02628776, 97.10439252, 99.32066924, 97.24584816,
       92.9267508 , 92.65657752, 93.87155456, 95.66253664, 95.17750125,
       90.93318132, 98.80084371, 98.37481387, 91.37294597, 91.6604946 ,
       95.08715803, 93.37126331, 94.20019732, 96.10020311, 98.29687616,
       93.24376389, 97.24130034, 89.03452725, 96.2832753 , 97.62787811,
       98.45723272, 95.46493436, 94.35373179, 96.02548256, 98.74767493,
       97.57544275, 92.5748759 , 91.37294597, 92.87730812, 97.85230675,
       93.87155456, 97.65393524, 92.75048583, 96.96851209, 99.14931546,
       99.35999981, 98.87007532, 95.85284217, 93.97853495, 97.21315663,
       96.74630281, 95.93799169, 97.59572169, 95.65982034, 85.98839623,
       95.19184343, 91.32093303, 92.0108226 , 97.75887636, 93.18884302,
       96.50342927, 99.58664719, 95.19184343, 93.83969256, 99.95827854,
       99.69982772, 88.80221141, 94.5081787 , 94.59300658, 96.34

---

#### Sorting

They also want to experiment with some more plotting techniques so they ask you to also deliver these datasets:
- values sorted in ascending order for each row
- values sorted in ascending order for each column
- the matrix of indices indicating the position in a sorted list of each value   
```
[3, 1, 2, 5, 4]  =>  [1, 2, 0, 4, 3]
```

In [11]:
# values sorted for each row
np.array([np.sort(row) for row in dataset])

array([[ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
         98.80833412,  99.14931546, 101.34745901, 104.03852715,
        107.43534677],
       [ 92.02628776,  92.65657752,  92.9267508 ,  93.87155456,
         97.10439252,  97.24584816,  99.32066924, 101.23162942,
        105.7197853 ],
       [ 90.93318132,  95.17750125,  95.66253664,  98.37481387,
         98.80084371, 105.95297652, 106.54654286, 107.22482426,
        110.18889465],
       [ 91.37294597,  91.6604946 ,  95.08715803, 100.40118279,
        100.96781394, 103.40412146, 105.48508838, 106.1472841 ,
        113.42090475],
       [ 93.37126331,  94.20019732,  96.10020311, 100.28690912,
        100.79478953, 101.20862522, 103.5730309 , 105.85269352,
        108.57980357],
       [ 89.03452725,  93.24376389,  96.2832753 ,  97.24130034,
         97.62787811,  98.29687616, 101.13442416, 102.80387079,
        104.60344836],
       [ 94.35373179,  95.46493436,  98.45723272, 100.07721494,
        100.72418901, 102.9758

> **Note:**   
By default, sorting will always be done along the last axis. In our case this is 1, leading to each row being sorted.

In [13]:
# values sorted for each column
np.array([np.sort(column) for column in dataset.T]).T

array([[ 91.37294597,  88.80221141,  90.93318132,  93.18884302,
         85.98839623,  91.6604946 ,  91.32093303,  92.5748759 ,
         91.37294597],
       [ 92.02628776,  91.6779221 ,  93.24376389,  94.59300658,
         89.03452725,  92.65657752,  93.04610867,  94.20019732,
         91.37294597],
       [ 94.11176915,  92.0108226 ,  93.83969256,  96.74630281,
         92.75048583,  95.19184343,  94.35373179,  94.76253572,
         93.87155456],
       [ 95.65982034,  92.87730812,  94.5081787 ,  97.24130034,
         92.9267508 ,  95.46493436,  96.50342927,  95.08715803,
         93.97853495],
       [ 95.66253664,  93.87155456,  97.75887636,  97.24584816,
         93.37126331,  95.62359311,  96.81964892,  95.85284217,
         95.19184343],
       [ 96.02548256,  94.57421727,  98.45723272,  97.62787811,
         93.97853495,  96.2832753 ,  96.89244283,  97.59572169,
         96.10020311],
       [ 96.10020311,  95.17750125,  99.32066924,  97.65393524,
         95.93799169,  96.3462

In [15]:
# indices of positions for each row
[f"Position: {index}, row:{row}" for index,row in enumerate(dataset)]

['Position: 0, row:[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914\n  98.80833412  96.81964892  98.56783189 101.34745901]',
 'Position: 1, row:[ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508\n  92.65657752 105.7197853  101.23162942  93.87155456]',
 'Position: 2, row:[ 95.66253664  95.17750125  90.93318132 110.18889465  98.80084371\n 105.95297652  98.37481387 106.54654286 107.22482426]',
 'Position: 3, row:[ 91.37294597 100.96781394 100.40118279 113.42090475 105.48508838\n  91.6604946  106.1472841   95.08715803 103.40412146]',
 'Position: 4, row:[101.20862522 103.5730309  100.28690912 105.85269352  93.37126331\n 108.57980357 100.79478953  94.20019732  96.10020311]',
 'Position: 5, row:[102.80387079  98.29687616  93.24376389  97.24130034  89.03452725\n  96.2832753  104.60344836 101.13442416  97.62787811]',
 'Position: 6, row:[106.71751618 102.97585605  98.45723272 100.72418901 106.39798503\n  95.46493436  94.35373179 106.83273763 100.07721494]',
 'Posit

---

#### Combining

After finishing their visualization and doing ask you to deliver a way they can incrementally add the split parts of the dataset to make sure it works with every subset, too.   
They want you to send them examples for:
- adding the second half of the first column
- adding the second column
- adding the third and last separate column


In [80]:
# split up dataset from activity03
thirds = np.hsplit(dataset, (3))
halfed_first = np.vsplit(thirds[0], (2))

# this is the part we've sent the client in activity03
halfed_first[0]

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132],
       [ 91.37294597, 100.96781394, 100.40118279],
       [101.20862522, 103.5730309 , 100.28690912],
       [102.80387079,  98.29687616,  93.24376389],
       [106.71751618, 102.97585605,  98.45723272],
       [ 96.02548256, 102.82360856, 106.47551845],
       [105.30350449,  92.87730812, 103.19258339],
       [110.44484313,  93.87155456, 101.5363647 ],
       [101.3514185 , 100.37372248, 106.6471081 ],
       [ 97.21315663, 107.02874163, 102.17642112]])

In [70]:
# adding the second half of the first column to the data


In [78]:
# adding the second column to our combined dataset


In [79]:
# adding the third column to our combined dataset


> **Note:**    
The same results can be achieved with `np.concatenate` and `np.stack`.    
For both methods, you need to provide the axis onto which it should be appended.   
Depending on your preferences you might want to use those.

---

#### Reshaping

For their internal AI algorithms, they need the dataset in a reshaped manner that reduces the number of columns.   
They asked us to deliver the whole dataset in the following shapes:
- reshaped in a one-dimensional list with all values
- reshaped in a matrix with only 2 columns

In [125]:
# reshaping to a list of values


In [126]:
# reshaping to a matrix with two columns


> **Note:**   
-1 in the dimension definition means that it figures out the other dimension on its own