Creating randomly generated datasets

In [1]:
from sklearn.datasets import make_regression

In [5]:
features, target, coefficient = make_regression(n_samples=100, n_features=3, n_informative=2, n_targets=1, noise=0.0, coef=True, random_state=1)

In [6]:
print(f"Feature matrix:\n{features[:3]}")
print(f"Target vector:\n{target[:3]}")

Feature matrix:
[[-1.1191154  -0.89055558  1.9560789 ]
 [ 0.84616065  0.31515939 -0.85951594]
 [ 0.58281521  0.04221375 -1.10061918]]
Target vector:
[-104.43925569   63.13782001   35.76065963]


In [7]:
coefficient

array([58.15774073, 44.19042807,  0.        ])

### Classification

In [8]:
from sklearn.datasets import make_classification

In [9]:
features, target = make_classification(n_samples=100, n_features=3, n_informative=3, n_redundant=0, n_classes=2, weights=[.25,.75], random_state=1)

In [10]:
print(f"Feature matrix: {features[:3]}")
print(f"Target vector: {target[:3]}")

Feature matrix: [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target vector: [1 0 0]


In [11]:
type(features)

numpy.ndarray

In [12]:
type(target)

numpy.ndarray

In [16]:
import pandas as pd
import numpy as np

In [28]:

dataframe_vector= np.column_stack((features, target))

df = pd.DataFrame(data=dataframe_vector)
df.head()

0         1         2    3
0  1.063548 -1.426322  1.021632  1.0
1  0.231570  1.495353  0.332516  0.0
2  0.159730  0.835335 -0.408696  0.0
3 -0.706121 -1.032810  1.394780  1.0
4  0.844490 -0.619972  1.087911  1.0

### Make BLOB example

In [29]:
from sklearn.datasets import make_blobs
features,classes=make_blobs(n_samples=100, centers=3, n_features=2, random_state=0)

In [31]:
print(features[:3])

[[2.63185834 0.6893649 ]
 [0.08080352 4.69068983]
 [3.00251949 0.74265357]]


In [32]:
print(classes[:3])

[1 0 1]


In [33]:
df = pd.DataFrame(data=features, columns=["Feature1", "Feature2"])
df["Cluster_id"]=classes

In [34]:
df.head()

Feature1  Feature2  Cluster_id
0  2.631858  0.689365           1
1  0.080804  4.690690           0
2  3.002519  0.742654           1
3 -0.637628  4.091047           0
4 -0.072283  2.883769           0

In [36]:
import plotly.express as px

fig = px.scatter(df, x="Feature1", y="Feature2", color="Cluster_id")
fig.show()

## SQLite using python

In [202]:
import sqlite3

In [203]:
conn=sqlite3.connect("./example.db")

In [204]:
cursor=conn.cursor()

In [205]:
sql = '''CREATE TABLE EMPLOYEE(
FIRST_NAME CHAR(20) NOT NULL,
LAST_NAME CHAR(20),
AGE INT NOT NULL,
SEX CHAR(1) ,
INCOME FLOAT
)
'''
cursor.execute(sql)
conn.commit()


OperationalError: table EMPLOYEE already exists

In [206]:
table_data =cursor.execute("select * from employee")
conn.commit()

print(table_data)

In [207]:
# table_data.fetchall()

In [208]:
add_sql = """Insert into employee(FIRST_NAME ,LAST_NAME ,AGE ,SEX,INCOME ) VALUES ('Prajwal', 'Luitel', 23, 'M', 3500)
"""
added_value=cursor.execute(add_sql)
conn.commit()

In [209]:
# added_value.fetchall()

### Adding more values and checking

In [210]:
add_sql = """Insert into employee(FIRST_NAME ,LAST_NAME ,AGE ,SEX,INCOME ) VALUES ('Rajan', 'Ghimire', 25, 'M', 20)
"""
cursor.execute(add_sql)
conn.commit()

In [211]:
# cursor.fetchall()

In [212]:
add_sql = """Insert into employee(FIRST_NAME ,LAST_NAME ,AGE ,SEX,INCOME ) VALUES ('Prajwal', 'Luitel', 23, 'M', 300)
"""
cursor.execute(add_sql)
conn.commit()

In [213]:
data = [
    ('Samridhi', 'Parajuli', 22, 'F', 300),
    ('Sagun', 'Dahal', 24, 'M', 70),
    ('Aarjeyan', 'Shrestha', 22, 'M', 38.90)
]



add_sql_2 = """Insert into employee(FIRST_NAME ,LAST_NAME ,AGE ,SEX,INCOME ) VALUES (?, ?, ?, ?, ?)
"""

cursor.executemany(add_sql_2, data)
conn.commit()


In [214]:
select_values = cursor.execute("SELECT * FROM EMPLOYEE")
conn.commit()

In [215]:
# [x for x in select_values]

In [216]:
select_values.fetchall()

[('Prajwal', 'Luitel', 23, 'M', 3500.0),
 ('Rajan', 'Ghimire', 25, 'M', 20.0),
 ('Prajwal', 'Luitel', 23, 'M', 300.0),
 ('Samridhi', 'Parajuli', 22, 'F', 300.0),
 ('Sagun', 'Dahal', 24, 'M', 70.0),
 ('Aarjeyan', 'Shrestha', 22, 'M', 38.9),
 ('Prajwal', 'Luitel', 23, 'M', 3500.0),
 ('Rajan', 'Ghimire', 25, 'M', 20.0),
 ('Prajwal', 'Luitel', 23, 'M', 300.0),
 ('Samridhi', 'Parajuli', 22, 'F', 300.0),
 ('Sagun', 'Dahal', 24, 'M', 70.0),
 ('Aarjeyan', 'Shrestha', 22, 'M', 38.9)]

## Update

In [217]:
sql = """UPDATE EMPLOYEE SET AGE=AGE+1 WHERE SEX='M'"""
cursor.execute(sql)

In [218]:
select_values = cursor.execute("SELECT * FROM EMPLOYEE")
conn.commit()
select_values.fetchall()

[('Prajwal', 'Luitel', 24, 'M', 3500.0),
 ('Rajan', 'Ghimire', 26, 'M', 20.0),
 ('Prajwal', 'Luitel', 24, 'M', 300.0),
 ('Samridhi', 'Parajuli', 22, 'F', 300.0),
 ('Sagun', 'Dahal', 25, 'M', 70.0),
 ('Aarjeyan', 'Shrestha', 23, 'M', 38.9),
 ('Prajwal', 'Luitel', 24, 'M', 3500.0),
 ('Rajan', 'Ghimire', 26, 'M', 20.0),
 ('Prajwal', 'Luitel', 24, 'M', 300.0),
 ('Samridhi', 'Parajuli', 22, 'F', 300.0),
 ('Sagun', 'Dahal', 25, 'M', 70.0),
 ('Aarjeyan', 'Shrestha', 23, 'M', 38.9)]

## Rename the column sex to gender

## Rename the whole table to your name

## 