### Class practice on 28/05/2024 - Advanced python programming
##### Prajwal Luitel (C0927658)

In [2]:
import numpy as np

In [3]:
vector_row = np.array([1,2,3])

In [4]:
vector = np.array([1,2,3,4,5,6])

In [5]:
vector[2]

3

### slicing

In [6]:
vector[2:5]

array([3, 4, 5])

In [7]:
vector[-4:-1]

array([3, 4, 5])

In [8]:
def get_index(vector, value):
    for i,el in enumerate(vector):
        if el==value:
            return i

In [9]:
get_index(vector, 3)

2

In [10]:
np.add(vector, 3)
vector

array([1, 2, 3, 4, 5, 6])

#### I want to retrieve indices for more than one occurrences

In [11]:
def get_index(vector, value):
    indices = []
    for i,el in enumerate(vector):
        if el==value:
            indices.append(i)
    return indices

In [12]:
get_index(np.array([1,2,3,4,5,6,3,3]), 3)

[2, 6, 7]

In [13]:
vector[::2]

array([1, 3, 5])

### Matrix

In [14]:
matrix = np.array([[1,2],[1,2],[1,2]])

In [15]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
matrix[1,1]

5

In [17]:
matrix[1,-1]

6

In [18]:
matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [19]:
def find_index(matrix, value):
    indices = []
    for i,el in enumerate(matrix):
        for j, el in enumerate(el):
            if matrix[i][j] == value:
                indices.append([i,j])
    return indices 


In [20]:
find_index(matrix, 6)

[[1, 2]]

### dot product of vectors

In [21]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
np.dot(vector_a, vector_b)

32

In [24]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])

In [25]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [26]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])