In [1]:
import numpy as np

In [2]:
# Different dimension variables

scalar = 1
scalar


1

In [3]:
vector = np.array([1,2])
vector

array([1, 2])

In [4]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [11]:
tensor = np.array([[[1, 2], [3,2]],[[1,7],[5,4]]])
tensor

array([[[1, 2],
        [3, 2]],

       [[1, 7],
        [5, 4]]])

In [12]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

matrix1+ matrix2


array([[ 6,  8],
       [10, 12]])

In [13]:
matrix1+7

array([[ 8,  9],
       [10, 11]])

In [20]:
matrix3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix3 + matrix2

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [21]:
#  Vector multiplication

matrix3 *4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [33]:
import numpy as np
import plotly.graph_objects as go

def plot_vectors_3d_interactive(vector_list):
    """
    Plots multiple vectors in 3D space interactively using Plotly.
    
    Parameters:
    vector_list (list of arrays): List of vectors (each vector is a NumPy array or list with 3 elements).
    """
    fig = go.Figure()

    # Plot each vector
    for i, vector in enumerate(vector_list):
        vector = np.array(vector)  # Ensure the vector is a NumPy array
        
        # Add a trace for the vector
        fig.add_trace(go.Scatter3d(
            x=[0, vector[0]],  # X-coordinates: start at 0, go to vector[0]
            y=[0, vector[1]],  # Y-coordinates: start at 0, go to vector[1]
            z=[0, vector[2]],  # Z-coordinates: start at 0, go to vector[2]
            mode='lines+markers',
            marker=dict(size=4),
            line=dict(width=5),
            name=f'Vector {i+1}'
        ))

    # Set axis labels and title
    fig.update_layout(
        title='Interactive 3D Vector Visualization',
        scene=dict(
            xaxis_title='X-axis',
            yaxis_title='Y-axis',
            zaxis_title='Z-axis'
        ),
        margin=dict(l=0, r=0, b=0, t=40)
    )

    # Show the interactive plot
    fig.show()



In [39]:
vector_a = np.array([10,20,30])
vector_b = np.array([5,-20,45])

dot_product = np.dot(vector_a, vector_b)
dot_product


1000

In [40]:
plot_vectors_3d_interactive([vector_a, vector_b])

In [41]:
# Compute the magnitude of vector b
magnitude_b = np.linalg.norm(vector_b)

# Compute the magnitude of the projection
magnitude_c = dot_product / magnitude_b

# Compute the projection vector c
projection_c = (dot_product / (magnitude_b ** 2)) * vector_b

print("Dot Product (a.b):", dot_product)
print("Magnitude of Vector b:", magnitude_b)
print("Magnitude of Projection (|c|):", magnitude_c)
print("Projection Vector (c):", projection_c)

Dot Product (a.b): 1000
Magnitude of Vector b: 49.49747468305833
Magnitude of Projection (|c|): 20.203050891044214
Projection Vector (c): [ 2.04081633 -8.16326531 18.36734694]


In [42]:
plot_vectors_3d_interactive([vector_a, vector_b, projection_c])