## Activity 02: Indexing, Slicing, and Iterating

Our client wants to prove that our dataset is nicely distributed around the mean value of 100.   
They asked us to run some tests on several subsections of it to make sure they won't get a non-descriptive section of our data.

Look at the mean value of each subtask.

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

---

#### Indexing

Since we need several rows of our dataset to complete the given task, we have to use indexing to get the right rows.   
To recap, we need: 
- the second row 
- the last row
- the first value of the first row
- the last value of the second to the last row

In [3]:
# indexing the second row of the dataset (2nd row)
print(f"The second row is: {dataset[1]}")

The second row is: [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
  92.65657752 105.7197853  101.23162942  93.87155456]


In [4]:
# indexing the last element of the dataset (last row)
print(f"The last row of dataset is: {dataset[-1]}")

The last row of dataset is: [ 94.11176915  99.62387832 104.51786419  97.62787811  93.97853495
  98.75108352 106.05042487 100.07721494 106.89005002]


In [5]:
# indexing the first value of the second row (1st row, 1st value)
print(f"The first value of the second row is: {dataset[1][0]}")

The first value of the second row is: 92.02628776


In [6]:
# indexing the last value of the second to last row (we want to use the combined access syntax here) 
print(f"The last value of second to last row is: {dataset[-2][-1]}")

The last value of second to last row is: 101.2226037


---

#### Slicing

Other than the single rows and values we also need to get some subsets of the dataset.   
Here we want slices:
- a 2x2 slice starting from the second row and second element to the 4th element in the 4th row
- every other element of the 5th row
- the content of the last row in reversed order

In [7]:
# slicing an intersection of 4 elements (2x2) of the first two rows and first two columns
print(f"The first two rows and first two columns are: {dataset[:2, :2]}")

The first two rows and first two columns are: [[ 99.14931546 104.03852715]
 [ 92.02628776  97.10439252]]


##### Why is it not a problem if such a small subsection has a bigger standard deviation from 100?

Several smaller values can cluster in such a small subsection leading to the value being really low.   
If we make our subsection larger, we have a higher chance of getting a more expressive view of our data.

In [9]:
# selecting every second element of the fifth row 
print(f"The second element of fifth row: {dataset[4, ::2]}")

The second element of fifth row: [101.20862522 100.28690912  93.37126331 100.79478953  96.10020311]


In [10]:
# reversing the entry order, selecting the first two rows in reversed order
print(f"The first two rows in reversed order is: {dataset[:2, ::-1]}")

The first two rows in reversed order is: [[101.34745901  98.56783189  96.81964892  98.80833412  98.74986914
   97.85230675 107.43534677 104.03852715  99.14931546]
 [ 93.87155456 101.23162942 105.7197853   92.65657752  92.9267508
   97.24584816  99.32066924  97.10439252  92.02628776]]


---

#### Splitting

Our client's team only wants to use a small subset of the given dataset.   
Therefore we need to first split it into 3 equal pieces and then give them the first half of the first split.   
They sent us this drawing to show us what they need:
```
1, 2, 3, 4, 5, 6          1, 2     3, 4    5, 6          1, 2  
3, 2, 1, 5, 4, 6    =>    3, 2     1, 5    4, 6    =>    3, 2    =>    1, 2
5, 3, 1, 2, 4, 3          5, 3     1, 2    4, 3                        3, 2
1, 2, 2, 4, 1, 5          1, 2     2, 4    1, 5          5, 3
                                                         1, 2
```

> **Note:**   
We are using a very small dataset here but imagine you have a huge amount of data and only want to look at a small subset of it to tweak your visualizations

In [12]:
# splitting up our dataset horizontally on indices one third and two thirds
horizontally_splitted_dataset = np.array_split(dataset, 3, axis=1)
# print(f"Splitted data: {horizontally_splitted_dataset}")
print(f"The first split: {horizontally_splitted_dataset[0]}")

The first split: [[ 99.14931546 104.03852715 107.43534677]
 [ 92.02628776  97.10439252  99.32066924]
 [ 95.66253664  95.17750125  90.93318132]
 [ 91.37294597 100.96781394 100.40118279]
 [101.20862522 103.5730309  100.28690912]
 [102.80387079  98.29687616  93.24376389]
 [106.71751618 102.97585605  98.45723272]
 [ 96.02548256 102.82360856 106.47551845]
 [105.30350449  92.87730812 103.19258339]
 [110.44484313  93.87155456 101.5363647 ]
 [101.3514185  100.37372248 106.6471081 ]
 [ 97.21315663 107.02874163 102.17642112]
 [ 95.65982034 107.22482426 107.19119932]
 [100.39303522  92.0108226   97.75887636]
 [103.1521596  109.40523174  93.83969256]
 [106.11454989  88.80221141  94.5081787 ]
 [ 96.78266211  99.84251605 104.03478031]
 [101.86186193 103.61720152  99.57859892]
 [ 97.49594839  96.59385486 104.63817694]
 [ 96.76814836  91.6779221  101.79132774]
 [106.89005002 106.57364584 102.26648279]
 [ 99.80873105 101.63973121 106.46476468]
 [ 96.10020311  94.57421727 100.80409326]
 [ 94.11176915  9

In [15]:
# splitting up our dataset vertically on index 2
vertically_splitted_dataset = np.array_split(horizontally_splitted_dataset, 2, axis=1)
print(f"The first split of vertically splitted data is: {vertically_splitted_dataset[0][0]}")

The first split of vertically splitted data is: [[ 99.14931546 104.03852715 107.43534677]
 [ 92.02628776  97.10439252  99.32066924]]


---

#### Iterating

Once you sent over the dataset they tell you that they also need a way iterate over the whole dataset element by element as if it would be a one-dimensional list.   
However, they want to also now the position in the dataset itself.

They send you this piece of code and tell you that it's not working as mentioned.   
Come up with the right solution for their needs.

In [12]:
# iterating over whole dataset (each value in each row)
curr_index = 0
for x in np.nditer(dataset):
    print(x, curr_index)
    curr_index += 1

NameError: name 'np' is not defined

In [13]:
# iterating over the whole dataset with indices matching the position in the dataset
